name: 'Build, Release, and Deploy to Cloud Run for ML Service'

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version tag (e.g., v0.1.1)'
        required: true
        default: 'v0.1.0'  # Optional: default version tag

env:
  PROJECT_ID: 'dicoding-submission-440805'
  REGION: 'asia-southeast2'
  SERVICE: 'bin-detective-ml'
  SERVICE_ACCOUNT: 'bindetective@dicoding-submission-440805.iam.gserviceaccount.com'  # Replace with your service account for Cloud Run
  CALLER_SERVICE_ACCOUNT: 'bindetective@dicoding-submission-440805.iam.gserviceaccount.com'
  MODEL_ARCHIVE_PATH: 'https://www.kaggle.com/api/v1/models/bahiskaraananda/robin-efficientnetv2s/tensorFlow2/1.0-18m-ft144/1/download'
  VERSION: ${{ github.event.inputs.version }}  # This will be populated when triggered manually

jobs:
  release_and_deploy:
    runs-on: 'ubuntu-latest'

    permissions:
      contents: write  # Allows creating a release
      id-token: write  # Allows authentication and deployment to Cloud Run

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v4'

      # Authenticate to Google Cloud using the service account key
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: google-github-actions/auth@v0
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
          token_format: 'access_token'

      - name: 'Set up Google Cloud SDK'
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: "${{ env.PROJECT_ID }}"

      # Docker authentication and build
      - name: 'Docker Auth'
        uses: 'docker/login-action@v1'
        with:
          username: _json_key
          password: ${{ secrets.GCP_SA_KEY }}
          registry: '${{ env.REGION }}-docker.pkg.dev'

      - name: 'Build and Push Container'
        run: |-
          DOCKER_TAG="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/bin-detective-ml/bin-detective-ml:${{ env.VERSION }}"
          docker build --tag "${DOCKER_TAG}" .
          docker push "${DOCKER_TAG}"

      # Deploy to Cloud Run
      - name: 'Deploy to Cloud Run'
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          service: '${{ env.SERVICE }}'
          region: 'asia-southeast2'
          image: 'asia-southeast2-docker.pkg.dev/dicoding-submission-440805/bin-detective-ml/bin-detective-ml:${{ env.VERSION }}'
          flags: >-
            --cpu=2
            --memory=2048Mi
            --min-instances=1
            --max-instances=1
            --set-env-vars MODEL_ARCHIVE_PATH=${{ env.MODEL_ARCHIVE_PATH }}
            --port=7976

      # Grant calling Cloud Run instance access
      - name: 'Grant invoker role to calling service'
        run: |
          gcloud run services add-iam-policy-binding ${{ env.SERVICE }} --region=${{ env.REGION }} --member=serviceAccount:${{ env.CALLER_SERVICE_ACCOUNT }} --role=roles/run.invoker


      # Create GitHub release for the specified version
      - name: 'Create GitHub Release'
        run: |-
          echo "Creating GitHub release for version ${{ env.VERSION }}"
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{
              "tag_name": "${{ env.VERSION }}",
              "target_commitish": "main",
              "name": "${{ env.VERSION }}",
              "body": "Release for version ${{ env.VERSION }} of Bin Detective ML service",
              "draft": false,
              "prerelease": false
            }' \
            "https://api.github.com/repos/${{ github.repository }}/releases"


      # Show the Cloud Run service URL (optional, for reference)
      - name: 'Show output'
        run: |
          echo ${{ steps.deploy.outputs.url }}
